server:
  port: 8083

spring:
  application:
    name: notification-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: akhileswarj@gmail.com
    password: gouzayjhvaneiqfx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  kafka:
    bootstrap-servers: localhost:19092,localhost:29092,localhost:39092
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/