server:
  port: 9090

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://${DB_HOST_PAYMENT:localhost}:3306/payments?createDatabaseIfNotExist=true
    username: ${DB_USERNAME_PAYMENT:your_db_username}
    password: ${DB_PASSWORD_PAYMENT:your_db_password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:19092,localhost:29092,localhost:39092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: payment-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

services:
  booking:
    url: http://localhost:8080

razorpay:
  key-id: your_razorpay_key_id
  key-secret: your_razorpay_key_secret
  callback-url: http://localhost:8765/payments
